name: Swedish Sniper Bot
on:
  schedule:
    - cron: '0 * * * *' # يعمل تلقائياً كل ساعة
  workflow_dispatch: # يتيح لك تشغيله يدوياً للتجربة

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: ambassadors/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install yfinance pandas python-telegram-bot
      - name: Run Bot
        run: python pro_stock_bot.py
